### ISSUE TITLE
Could you share the original non-zoomed logo?

### ISSUE THREAD

**Issue by carlinmack** [qaware/isabelle-afp-search#1]
Hi, I'm working on improving the existing AFP and would like to update the logo. `isabelle logo` outputs the following which is super gross:

![image](https://user-images.githubusercontent.com/6676843/94428647-0e65b700-015f-11eb-931f-db5537e49a4c.png)

and I can't seem to find the clean version you used.

Many thanks,
if you would prefer to email you can reach me at carlinmack@pm.me

**Comment by Dacit** [comment]
For anyone wondering, an unofficial high-res version of the logo can be found, for instance, [here](https://www21.in.tum.de/hakyll-assets/isabelle.svg).
